# Tier 1 #2 — expanded course titles, keyed by catnum.
# Rules: MECH-2040 verbatim; cross-listed courses keep identical titles across
# departments; a LAB paired with a same-titled LEC becomes "<lecture> Laboratory";
# no lecture is titled "Lab"; no two lectures in one department share a title.
TITLES = {
    # --- Aeronautical ---
    "AERO-1005": "Experimental Methods in Aerospace Engineering I",
    "AERO-1010": "Aerospace Engineering Laboratory I",
    "AERO-1015": "Aerodynamics",
    "AERO-1020": "Computational Methods in Aerospace Engineering",
    "AERO-1025": "Finite Element Method I",
    "AERO-1030": "Introduction to Aerospace Engineering Systems",
    "AERO-1035": "Introduction to Aerospace Engineering Systems Laboratory",
    "AERO-1040": "Introduction to Turbulent Flow",
    "AERO-1045": "Introduction to Aeronautics",
    "AERO-1050": "Introduction to Gas Dynamics",
    "AERO-2005": "Experimental Methods in Aerospace Engineering II",
    "AERO-2010": "Aerospace Engineering Laboratory II",
    "AERO-2015": "Aerospace Systems Design",
    "AERO-2020": "Aerospace Propulsion",
    "AERO-2025": "Aerospace Structures",
    "AERO-2030": "Aircraft Dynamics and Control",
    "AERO-2035": "Computational Fluid Dynamics II",
    "AERO-3005": "Gas-Turbine Propulsion",
    "AERO-3010": "Molecular Gas Dynamics",
    "AERO-3015": "Multidisciplinary Design Optimization",
    "AERO-3020": "Structural Dynamics",
    "AERO-4005": "Solid Mechanics and Aerospace Structures",
    "AERO-4010": "Space Systems Design and Management",
    "AERO-4015": "Special Topics in Flight Dynamics and Control",
    "AERO-4020": "Special Topics in Gas Dynamics",
    # --- Chemical ---
    "CHEM-1005": "Chemical Engineering Laboratory I",
    "CHEM-1010": "Chemical Engineering Unit Operations I",
    "CHEM-1015": "Chemical Engineering Thermodynamics",
    "CHEM-1020": "Engineering Statistics and Problem Solving",
    "CHEM-1025": "Introduction to Transport Phenomena",
    "CHEM-2005": "Biopharmaceutical Engineering",
    "CHEM-2010": "Chemical Process Economics",
    "CHEM-2015": "Chemical Engineering Unit Operations II",
    "CHEM-2020": "Chemical Engineering Laboratory II",
    "CHEM-2025": "Chemical Product Design II",
    "CHEM-3005": "Fluid Mechanics",
    "CHEM-3010": "Global Quality Systems",
    "CHEM-3015": "Physics of Polymers",
    "CHEM-3020": "Research and Special Problems",
    "CHEM-3025": "Advanced Research and Special Problems",
    "CHEM-3030": "Advances in Tissue Engineering",
    "CHEM-4005": "Process Simulation and Design",
    "CHEM-4010": "Reaction Engineering Design",
    "CHEM-4015": "Reactor Engineering",
    "CHEM-4020": "Selected Topics in Chemical Engineering",
    "CHEM-4025": "Special Topics in Chemical Engineering I",
    "CHEM-4030": "Special Topics in Chemical Engineering II",
    # --- Civil ---
    "CIVL-1005": "Fundamentals of Air Quality Engineering",
    "CIVL-1010": "Aquatic Chemistry",
    "CIVL-1015": "Aquatic Chemistry Laboratory",
    "CIVL-1020": "Biological Processes in Environmental Engineering",
    "CIVL-1025": "Building Information Modeling",
    "CIVL-1030": "Civil Engineering Materials Laboratory",
    "CIVL-1035": "Civil Engineering Materials",
    "CIVL-1040": "Fluid Mechanics",
    "CIVL-1045": "Fluid Mechanics Laboratory",
    "CIVL-1050": "Industrial Ecology",
    "CIVL-1055": "Infrastructure Sensing",
    "CIVL-1060": "Principles of Sustainable Engineering",
    "CIVL-2005": "Computational Methods in Engineering Laboratory",
    "CIVL-2010": "Computational Methods in Engineering",
    "CIVL-2015": "Design of Hydraulic Systems",
    "CIVL-2020": "Environmental Engineering Laboratory",
    "CIVL-2025": "Environmental Engineering Analysis",
    "CIVL-2030": "Geotechnical Engineering",
    "CIVL-2035": "Geotechnical Engineering Laboratory",
    "CIVL-2040": "Plastic Analysis and Design",
    "CIVL-2045": "Sensors and Circuits Laboratory",
    "CIVL-2050": "Sensors and Circuits",
    "CIVL-3005": "Construction Contracting",
    "CIVL-3010": "Construction Contracting Laboratory",
    "CIVL-3015": "Data Analysis in Civil and Environmental Engineering",
    "CIVL-3020": "Design of Reinforced Concrete Structures Laboratory",
    "CIVL-3025": "Design of Reinforced Concrete Structures",
    "CIVL-3030": "Environmental Process Engineering",
    "CIVL-3035": "Excavation and Tunneling",
    "CIVL-3040": "Prestressed Concrete",
    "CIVL-3045": "Professional Issues and Design",
    "CIVL-3050": "Structural Reliability",
    "CIVL-3055": "Statics and Dynamics",
    "CIVL-4005": "Advanced Soil Mechanics",
    "CIVL-4010": "Construction Engineering Research",
    "CIVL-4015": "Construction Engineering and Equipment",
    "CIVL-4020": "Energy Infrastructure Systems",
    "CIVL-4025": "Hydraulic and Hydrologic Engineering Research",
    "CIVL-4030": "Slopes, Dams, and Retaining Structures",
    "CIVL-4035": "Solid and Structural Mechanics",
    "CIVL-4040": "Special Topics in Civil and Environmental Engineering",
    "CIVL-4045": "Sustainable Cities",
    # --- Computer Science ---
    "COMP-1005": "Algorithms",
    "COMP-1010": "Computer Architecture Laboratory",
    "COMP-1015": "Computer Architecture",
    "COMP-1020": "Computer Vision",
    "COMP-1025": "Data Structures and Algorithms",
    "COMP-1030": "Data Structures and Algorithms Laboratory",
    "COMP-1035": "Foundations of Computer Science",
    "COMP-1040": "Introduction to Computer Security Laboratory",
    "COMP-1045": "Introduction to Computer Security",
    "COMP-1050": "Introduction to Computer Organization",
    "COMP-2005": "Introduction to Machine Learning",
    "COMP-2010": "Introduction to Operating Systems",
    "COMP-2015": "Computer Game Design",
    "COMP-2020": "Computer Network Security Laboratory",
    "COMP-2025": "Computer Network Security",
    "COMP-2030": "Compiler Construction",
    "COMP-2035": "Database Management Systems",
    "COMP-2040": "Machine Learning",
    "COMP-3005": "Programming and Data Structures",
    "COMP-3010": "Programming and Data Structures Laboratory",
    "COMP-3015": "Computational Models of Cognition",
    "COMP-3020": "Foundations of Computer Vision",
    "COMP-3025": "Parallel Computer Architecture",
    "COMP-3030": "Software Engineering",
    "COMP-4005": "Foundations of Artificial Intelligence",
    "COMP-4010": "Advanced Artificial Intelligence",
    "COMP-4015": "User Interface Development",
    "COMP-4020": "Web Systems Laboratory",
    "COMP-4025": "Web Systems",
    # --- Core curriculum ---
    "CORE-1005": "American History",
    "CORE-1010": "Calculus",
    "CORE-1015": "English Literature",
    "CORE-1020": "Financial Accounting",
    "CORE-2005": "Finance",
    "CORE-2010": "General Management",
    "CORE-2015": "Business Law",
    "CORE-2020": "Probability and Statistics",
    # --- Electrical ---
    "EENG-1005": "Amorphous Semiconductor Devices",
    "EENG-1010": "Analog Circuits",
    "EENG-1015": "Analog Circuits Laboratory",
    "EENG-1020": "Analog Integrated Circuits",
    "EENG-1025": "Antenna Theory and Design",
    "EENG-1030": "Control Systems Analysis and Design",
    "EENG-1035": "Electric Circuits, Systems, and Applications",
    "EENG-1040": "Electric Circuits, Systems, and Applications Laboratory",
    "EENG-1045": "Elementary Programming Concepts",
    "EENG-1050": "Elementary Programming Concepts Laboratory",
    "EENG-1055": "Integrated Microsystems Design and Fabrication",
    "EENG-1060": "Integrated Microsystems Laboratory",
    "EENG-1065": "Integrated Microsystems",
    "EENG-1070": "Introduction to Semiconductor Devices",
    "EENG-1075": "Introduction to Digital Signal Processing",
    "EENG-1080": "Introduction to Embedded System Design",
    "EENG-1085": "Introduction to Embedded System Design Laboratory",
    "EENG-1090": "Introduction to Logic Design Laboratory",
    "EENG-1095": "Introduction to Logic Design",
    "EENG-2005": "Introduction to Signals and Systems Laboratory",
    "EENG-2010": "Introduction to Signals and Systems",
    "EENG-2015": "Introduction to Antennas Laboratory",
    "EENG-2020": "Introduction to Antennas",
    "EENG-2025": "Introduction to Electric Circuits Laboratory",
    "EENG-2030": "Introduction to Electric Circuits",
    "EENG-2035": "Applied Quantum Mechanics II",
    "EENG-2040": "Communication Networks",
    "EENG-2045": "Digital System Testing",
    "EENG-2050": "Electric Machines and Drives",
    "EENG-2055": "Electric Machines and Drives Laboratory",
    "EENG-2060": "Lasers",
    "EENG-2065": "Logic Circuit Synthesis and Optimization",
    "EENG-2070": "Principles of Optics",
    "EENG-2075": "Probabilistic Methods in Engineering",
    "EENG-3005": "Production Systems Engineering",
    "EENG-3010": "Semiconductor Optoelectronic Devices",
    "EENG-3015": "Semiconductor Optoelectronic Devices Laboratory",
    "EENG-3020": "VLSI Design I Laboratory",
    "EENG-3025": "VLSI Design I",
    "EENG-3030": "Autonomous Robotics",
    "EENG-3035": "Autonomous Robotics Laboratory",
    "EENG-3040": "Digital Signal Processing Design",
    "EENG-3045": "Digital Signal Processing Design Laboratory",
    "EENG-3050": "Electronic Sensing Systems Laboratory",
    "EENG-3055": "Electronic Sensing Systems",
    "EENG-3060": "Embedded Control Laboratory",
    "EENG-3065": "Embedded Control",
    "EENG-3070": "Experimental Plasma Physics Laboratory",
    "EENG-3075": "Experimental Plasma Physics",
    "EENG-4005": "Programming for Scientists and Engineers",
    "EENG-4010": "Radiowave Propagation Laboratory",
    "EENG-4015": "Radiowave Propagation",
    "EENG-4020": "VLSI Design II Laboratory",
    "EENG-4025": "VLSI Design II",
    "EENG-4030": "Advanced Laser Systems Laboratory",
    "EENG-4035": "Advanced Laser Systems",
    "EENG-4040": "Advanced Solid-State Microwave Circuits",
    "EENG-4045": "Design of Digital Control Systems",
    "EENG-4050": "Digital Integrated Circuits",
    "EENG-4055": "Electro-Optic Semiconductors",
    "EENG-4060": "Engineering Electromagnetics Laboratory",
    "EENG-4065": "Engineering Electromagnetics",
    "EENG-4070": "Hands-On Robotics Laboratory",
    "EENG-4075": "Hands-On Robotics",
    "EENG-4080": "Patent Fundamentals for Engineers",
    "EENG-4085": "Plasmonics",
    "EENG-4090": "Solid-State Devices",
    # --- Manufacturing ---
    "MANU-1005": "Composite Materials",
    "MANU-1010": "Design and Manufacturing I Laboratory",
    "MANU-1015": "Design and Manufacturing I",
    "MANU-1020": "Material Handling Systems",
    "MANU-1025": "Materials Engineering Design",
    "MANU-1030": "Materials Engineering Design Laboratory",
    "MANU-2005": "Derivative Instruments and Commodity Risk",
    "MANU-2010": "Design and Manufacturing II Laboratory",
    "MANU-2015": "Design and Manufacturing II",
    "MANU-2020": "Design Optimization",
    "MANU-2025": "Fatigue in Mechanical Design",
    "MANU-2030": "Lean Manufacturing and Services",
    "MANU-2035": "Machining Processes",
    "MANU-2040": "Marine Structure Construction",
    "MANU-2045": "Manufacturing and Supply Operations",
    "MANU-2050": "Statistical Quality Control",
    "MANU-3005": "Design and Manufacturing III",
    "MANU-3010": "Design and Manufacturing Capstone",
    "MANU-3015": "Design for Manufacturing",
    "MANU-3020": "Global Manufacturing",
    "MANU-3025": "Manufacturing System Design",
    "MANU-3030": "Production Systems Engineering",
    "MANU-3035": "Statistical Quality Control II",
    "MANU-4005": "Advanced Mechatronics for Manufacturing",
    "MANU-4010": "Design Problems",
    "MANU-4015": "Manufacturing Project",
    "MANU-4020": "Production and Inventory Control",
    "MANU-4025": "Scheduling",
    "MANU-4030": "Supply Chain Facilities",
    "MANU-4035": "Industrial Operations Project",
    # --- Materials ---
    "MATL-1005": "Ceramic Materials",
    "MATL-1010": "Composite Materials",
    "MATL-1015": "Electron Microscopy I Laboratory",
    "MATL-1020": "Electron Microscopy I",
    "MATL-1025": "Introduction to Materials and Manufacturing",
    "MATL-2005": "Physics of Polymers",
    "MATL-2010": "Physics of Materials",
    "MATL-2015": "Principles of Engineering Materials",
    "MATL-2020": "Kinetics and Transport in Materials",
    "MATL-2025": "Materials Physical Chemistry",
    "MATL-2030": "Materials Characterization II",
    "MATL-3005": "Materials Characterization II Laboratory",
    "MATL-3010": "Physical Metallurgy",
    "MATL-3015": "Polymeric Materials",
    "MATL-3020": "Materials Engineering Design Laboratory",
    "MATL-4005": "Materials Engineering Design",
    "MATL-4010": "Design Problems",
    # --- Mechanical ---
    "MECH-1005": "Dynamics",
    "MECH-1010": "Mechanical Vibrations",
    "MECH-1015": "Introduction to Finite Elements",
    "MECH-1020": "Introduction to Solid Mechanics",
    "MECH-1025": "Modeling and Control of Dynamic Systems",
    "MECH-1030": "Thermodynamics I",
    "MECH-2035": "Battery Systems and Control",
    "MECH-2040": "Biofluid Mechanics",
    "MECH-2045": "Contact Mechanics",
    "MECH-2050": "Design for Manufacturing",
    "MECH-2055": "Fluid Mechanics I",
    "MECH-2060": "Mechanical Behavior of Materials",
    "MECH-2065": "Design of Manufacturing Systems",
    "MECH-2070": "Statistical Quality Control",
    "MECH-2075": "Strength of Materials",
    "MECH-3005": "Advanced Fluid Mechanics II",
    "MECH-3010": "Analytical and Computational Dynamics I",
    "MECH-3015": "Design of Digital Control Systems",
    "MECH-3020": "Design Optimization",
    "MECH-3025": "Fatigue in Mechanical Design",
    "MECH-3030": "Fluid Mechanics II",
    "MECH-3035": "Heat Transfer",
    "MECH-3040": "Linear Systems Theory",
    "MECH-3045": "Machining Processes",
    "MECH-3050": "Mechanical Engineering Analysis",
    "MECH-3055": "Sustainable Design",
    "MECH-4005": "Advanced Energy Solutions",
    "MECH-4010": "Advanced Internal Combustion Engines",
    "MECH-4015": "Advanced Mechatronics for Manufacturing",
    "MECH-4020": "Global Manufacturing",
    "MECH-4025": "Hybrid Electric Vehicles",
    "MECH-4030": "Special Topics in Mechanical Engineering Laboratory",
    "MECH-4035": "Special Topics in Mechanical Engineering",
    "MECH-4040": "Special Topics in Mechanical Engineering II",
    # --- Nuclear ---
    "NUCL-1005": "Computational Fluid Dynamics for Nuclear Applications",
    "NUCL-1010": "Computational Radiation Imaging",
    "NUCL-1015": "Fluid Mechanics for Nuclear Engineering",
    "NUCL-1020": "Fundamentals of Nuclear Engineering and Radiological Sciences",
    "NUCL-1025": "Introduction to Nuclear Engineering",
    "NUCL-1030": "Nuclear Core Design and Analysis I",
    "NUCL-1035": "Nuclear Instrumentation Laboratory",
    "NUCL-1040": "Nuclear Instrumentation",
    "NUCL-1045": "Principles of Radiation Imaging",
    "NUCL-2005": "Applied Radiation Measurement",
    "NUCL-2010": "Applied Radiation Measurement Laboratory",
    "NUCL-2015": "Applications of Radiation Laboratory",
    "NUCL-2020": "Applications of Radiation",
    "NUCL-2025": "Fusion Reactor Technology",
    "NUCL-2030": "Nuclear Engineering and Radiological Sciences II",
    "NUCL-2035": "Nuclear Reactor Kinetics",
    "NUCL-2040": "Nuclear Fuels",
    "NUCL-2045": "Plasma Physics II",
    "NUCL-2050": "Experimental Plasma Physics",
    "NUCL-2055": "Experimental Plasma Physics Laboratory",
    "NUCL-3005": "Medical Radiation Health Engineering",
    "NUCL-3010": "Nuclear Power Reactors",
    "NUCL-3015": "Nuclear Measurement Methods",
    "NUCL-3020": "Plasma Engineering",
    "NUCL-3025": "Research in Nuclear Engineering and Radiological Sciences",
    "NUCL-4005": "Radiation Safety and Medical Physics Practicum",
    "NUCL-4010": "Radiation Therapy Physics",
    "NUCL-4015": "Radiation Shielding",
    "NUCL-4020": "Radiological Physics and Dosimetry",
}
