set schema 'ku';
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('00', 'Unknown', 255);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('US', 'UNITED STATES', 1);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CA', 'CANADA', 2);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GB', 'UNITED KINGDOM', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('RU', 'RUSSIAN FEDERATION', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CN', 'CHINA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('JP', 'JAPAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KR', 'KOREA, REPUBLIC OF', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KP', 'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MX', 'MEXICO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('DE', 'GERMANY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('ES', 'SPAIN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('FR', 'FRANCE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('FI', 'FINLAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('IS', 'ICELAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AU', 'AUSTRALIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AF', 'AFGHANISTAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AX', 'ALAND ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AL', 'ALBANIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('DZ', 'ALGERIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AS', 'AMERICAN SAMOA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AD', 'ANDORRA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AO', 'ANGOLA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AI', 'ANGUILLA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AQ', 'ANTARCTICA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AG', 'ANTIGUA AND BARBUDA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AR', 'ARGENTINA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AM', 'ARMENIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AW', 'ARUBA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AT', 'AUSTRIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AZ', 'AZERBAIJAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BS', 'BAHAMAS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BH', 'BAHRAIN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BD', 'BANGLADESH', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BB', 'BARBADOS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BY', 'BELARUS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BE', 'BELGIUM', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BZ', 'BELIZE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BJ', 'BENIN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BM', 'BERMUDA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BT', 'BHUTAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BO', 'BOLIVIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BA', 'BOSNIA AND HERZEGOVINA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BW', 'BOTSWANA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BV', 'BOUVET ISLAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BR', 'BRAZIL', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('IO', 'BRITISH INDIAN OCEAN TERRITORY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BN', 'BRUNEI DARUSSALAM', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BG', 'BULGARIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BF', 'BURKINA FASO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('BI', 'BURUNDI', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KH', 'CAMBODIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CM', 'CAMEROON', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CV', 'CAPE VERDE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KY', 'CAYMAN ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CF', 'CENTRAL AFRICAN REPUBLIC', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TD', 'CHAD', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CL', 'CHILE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CX', 'CHRISTMAS ISLAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CC', 'COCOS (KEELING) ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CO', 'COLOMBIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KM', 'COMOROS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CG', 'CONGO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CD', 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CK', 'COOK ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CR', 'COSTA RICA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CI', 'COTE D''IVOIRE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('HR', 'CROATIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CU', 'CUBA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CY', 'CYPRUS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CZ', 'CZECH REPUBLIC', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('DK', 'DENMARK', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('DJ', 'DJIBOUTI', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('DM', 'DOMINICA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('DO', 'DOMINICAN REPUBLIC', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('EC', 'ECUADOR', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('EG', 'EGYPT', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SV', 'EL SALVADOR', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GQ', 'EQUATORIAL GUINEA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('ER', 'ERITREA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('EE', 'ESTONIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('ET', 'ETHIOPIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('FK', 'FALKLAND ISLANDS (MALVINAS)', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('FO', 'FAROE ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('FJ', 'FIJI', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GF', 'FRENCH GUIANA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PF', 'FRENCH POLYNESIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TF', 'FRENCH SOUTHERN TERRITORIES', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GA', 'GABON', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GM', 'GAMBIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GE', 'GEORGIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GH', 'GHANA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GI', 'GIBRALTAR', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GR', 'GREECE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GL', 'GREENLAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GD', 'GRENADA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GP', 'GUADELOUPE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GU', 'GUAM', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GT', 'GUATEMALA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GG', 'GUERNSEY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GN', 'GUINEA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GW', 'GUINEA-BISSAU', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GY', 'GUYANA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('HT', 'HAITI', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('HM', 'HEARD ISLAND AND MCDONALD ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('VA', 'HOLY SEE (VATICAN CITY STATE)', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('HN', 'HONDURAS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('HK', 'HONG KONG', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('HU', 'HUNGARY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('IN', 'INDIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('ID', 'INDONESIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('IR', 'IRAN, ISLAMIC REPUBLIC OF', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('IQ', 'IRAQ', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('IE', 'IRELAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('IM', 'ISLE OF MAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('IL', 'ISRAEL', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('IT', 'ITALY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('JM', 'JAMAICA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('JE', 'JERSEY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('JO', 'JORDAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KZ', 'KAZAKHSTAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KE', 'KENYA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KI', 'KIRIBATI', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KW', 'KUWAIT', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KG', 'KYRGYZSTAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LA', 'LAO PEOPLE''S DEMOCRATIC REPUBLIC', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LV', 'LATVIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LB', 'LEBANON', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LS', 'LESOTHO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LR', 'LIBERIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LY', 'LIBYAN ARAB JAMAHIRIYA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LI', 'LIECHTENSTEIN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LT', 'LITHUANIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LU', 'LUXEMBOURG', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MO', 'MACAO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MK', 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MG', 'MADAGASCAR', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MW', 'MALAWI', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MY', 'MALAYSIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MV', 'MALDIVES', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('ML', 'MALI', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MT', 'MALTA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MH', 'MARSHALL ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MQ', 'MARTINIQUE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MR', 'MAURITANIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MU', 'MAURITIUS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('YT', 'MAYOTTE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('FM', 'MICRONESIA, FEDERATED STATES OF', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MD', 'MOLDOVA, REPUBLIC OF', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MC', 'MONACO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MN', 'MONGOLIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MS', 'MONTSERRAT', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MA', 'MOROCCO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MZ', 'MOZAMBIQUE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MM', 'MYANMAR', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NA', 'NAMIBIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NR', 'NAURU', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NP', 'NEPAL', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NL', 'NETHERLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AN', 'NETHERLANDS ANTILLES', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NC', 'NEW CALEDONIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NZ', 'NEW ZEALAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NI', 'NICARAGUA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NE', 'NIGER', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NG', 'NIGERIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NU', 'NIUE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NF', 'NORFOLK ISLAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('MP', 'NORTHERN MARIANA ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('NO', 'NORWAY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('OM', 'OMAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PK', 'PAKISTAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PW', 'PALAU', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PS', 'PALESTINIAN TERRITORY, OCCUPIED', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PA', 'PANAMA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PG', 'PAPUA NEW GUINEA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PY', 'PARAGUAY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PE', 'PERU', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PH', 'PHILIPPINES', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PN', 'PITCAIRN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PL', 'POLAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PT', 'PORTUGAL', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PR', 'PUERTO RICO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('QA', 'QATAR', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('RE', 'REUNION', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('RO', 'ROMANIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('RW', 'RWANDA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SH', 'SAINT HELENA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('KN', 'SAINT KITTS AND NEVIS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LC', 'SAINT LUCIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('PM', 'SAINT PIERRE AND MIQUELON', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('VC', 'SAINT VINCENT AND THE GRENADINES', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('WS', 'SAMOA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SM', 'SAN MARINO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('ST', 'SAO TOME AND PRINCIPE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SA', 'SAUDI ARABIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SN', 'SENEGAL', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('RS', 'SERBIA AND MONTENEGRO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SC', 'SEYCHELLES', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SL', 'SIERRA LEONE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SG', 'SINGAPORE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SK', 'SLOVAKIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SI', 'SLOVENIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SB', 'SOLOMON ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SO', 'SOMALIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('ZA', 'SOUTH AFRICA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('GS', 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('LK', 'SRI LANKA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SD', 'SUDAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SR', 'SURINAME', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SJ', 'SVALBARD AND JAN MAYEN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SZ', 'SWAZILAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SE', 'SWEDEN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('CH', 'SWITZERLAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('SY', 'SYRIAN ARAB REPUBLIC', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TW', 'TAIWAN, PROVINCE OF CHINA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TJ', 'TAJIKISTAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TZ', 'TANZANIA, UNITED REPUBLIC OF', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TH', 'THAILAND', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TL', 'TIMOR-LESTE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TG', 'TOGO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TK', 'TOKELAU', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TO', 'TONGA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TT', 'TRINIDAD AND TOBAGO', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TN', 'TUNISIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TR', 'TURKEY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TM', 'TURKMENISTAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TC', 'TURKS AND CAICOS ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('TV', 'TUVALU', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('UG', 'UGANDA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('UA', 'UKRAINE', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('AE', 'UNITED ARAB EMIRATES', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('UM', 'UNITED STATES MINOR OUTLYING ISLANDS', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('UY', 'URUGUAY', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('UZ', 'UZBEKISTAN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('VU', 'VANUATU', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('VE', 'VENEZUELA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('VN', 'VIET NAM', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('VG', 'VIRGIN ISLANDS, BRITISH', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('VI', 'VIRGIN ISLANDS, U.S.', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('WF', 'WALLIS AND FUTUNA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('EH', 'WESTERN SAHARA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('YE', 'YEMEN', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('ZM', 'ZAMBIA', 10);
INSERT INTO cd_country(cd_country, name_country, sort_order) VALUES ('ZW', 'ZIMBABWE', 10);
